# install prefix
PREFIX ?=

# project name (directory name is used if left blank)
PROJECT = exe

# project version
VERSION    = 1
SUBVERSION = 0
PATCHLEVEL = 0

# library and include paths (space separated value)
LIBRARY_DIR =
INCLUDE_DIR =

# static and shared libraries to be linked (space separated values)
STATIC_LIBRARIES =
SHARED_LIBRARIES =

# compiler and compiler flags
CXXFLAGS = -w -std=c++11
CFLAGS   = -w
O        = -O3
